# This file stores the mod's metadata.
modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/LoneStryder/terafor/issues"

[[mods]]
modId="terafor"
version="${file.jarVersion}"
displayName="Terafor"
#updateJSONURL="https://github.com/LoneStryder/terafor/blob/main/updates.json" | Currently Unused
#displayURL="https://www.curseforge.com/minecraft/mc-mods/terafor" | Currently Unused
logoFile="terafor.png"
credits="Thanks to Terraria for inspiration."
authors="Stryder"
description='''
An in-development mod aiming to improve and build upon the vanilla experience.
'''

[[dependencies.terafor]]
	modId="forge"
	mandatory=true
	versionRange="[36,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.terafor]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.5,1.17)"
	ordering="NONE"
	side="BOTH"
